name: Sync Upstream and Overwrite File

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # 每天 0 点触发
  
jobs:
  sync_and_overwrite:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        
      - name: Set Up Git User
        run: |
          git config user.name "${{ secrets.GIT_USER_NAME }}"
          git config user.email "${{ secrets.GIT_USER_EMAIL }}"

      - name: Add Upstream Remote
        run: |
          git remote add upstream https://github.com/unifreq/openwrt_packit.git
          git fetch upstream

      - name: Overwrite File
        run: |
          # 从上游拉取最新的代码
          git fetch upstream
          git checkout master
          git reset --hard upstream/master
          git merge --allow-unrelated-histories upstream/master
          
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  cleaning:
    if: ${{ always() }}
    needs: [sync_and_overwrite]
    runs-on: ubuntu-latest
    steps:
    - name: Delete workflow runs
      uses: GitRML/delete-workflow-runs@main
      with:
        retain_days: 1
        keep_minimum_runs: 1